# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site settings
title: GnG Landing Page
email: PhantasmicJ@GamersNGhosts.com
description: "A simple page with a large image and social links."
baseurl: "" # if your site is in a subfolder, change this
url: "https://phantasmicj.github.io"
github_username: PhantasmicJ

# Build settings
markdown: kramdown
theme: minima # Or a theme that suits your needs
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Front Matter Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default" # Create a custom default layout if needed

# Custom data (for social links)
social:
  - name: Facebook
    url: "https://www.facebook.com/profile.php?id=61567546343660&"
    image: "/assets/images/facebook-icon.png" # Path to your Twitter icon
  - name: Instagram
    url: "https://www.instagram.com/gamersnghosts"
    image: "/assets/images/instagram-icon.png" # Path to your Instagram icon
  - name: YouTube
    url: "https://www.youtube.com/@GamersNGhosts"
    image: "/assets/images/youtube-icon.png" # Path to your GitHub icon
  - name: Twitch
    url: "https://www.twitch.tv/gamersnghosts"
    image: "/assets/images/twitch-icon.png" # Path to your LinkedIn icon

# Custom variables for use in templates
image_path: "/assets/images/large-image.png" # Path to your large image

